### ISSUE TITLE
use TLS for the rendezvous connection

### ISSUE THREAD

**Issue by warner** [magic-wormhole/magic-wormhole#144]
It'd be a good idea to use TLS for the client's connection to the Rendezvous server. It doesn't actually protect that much, which is why it hasn't been a priority for me before:

* an eavesdropper watching the client's connection can still tell that they're using magic-wormhole, because the packets are aimed at the (public) rendezvous server's IP address
* an eavesdropper watching the server can correlate the traffic in and out to determine that client at IP-1 is talking to the client at IP-2, even if the messages themselves are encrypted
* an eavesdropper who can listen to two likely communication partners at the same time will be able to tell that they're talking wormhole to each other, based on the timing correlation, without even looking at the server

You need Tor to protect against the first one, and even then I suspect the message pattern is distinctive enough that an eavesdropper could figure it out.

To protect against the second two, in addition to TLS (to hide the exact channel/nameplate in use) and plenty of cover traffic, we also need clients to not be online at the same time (doing something like Pond's randomly-timed server connections, and fixed-size messages). This will require a feature I'm working on called "journaled mode" to work at all.

But adding TLS is still the right thing to do. On the client side, this is pretty simple: when we parse the rendezvous server URL, make sure we can accept `wss:` in addition to just `ws:`, build a `tcp:` or `tls:` endpoint descriptor string to match, then pass that string into `endpoints.clientFromString` instead of always using `HostnameEndpoint`. (we do need to enhance the TorManager to handle this too, running TLS over Tor over TCP, which might require changes to txtorcon, I'm not sure).

On the server side, wormhole-server needs to use txsni or an `endpoints.SSL4ServerEndpoint` instead of always using `TCP4ServerEndpoint`.

To get a valid certificate for the public rendezvous server, I plan to use LetsEncrypt. I had originally thought this would require changes to wormhole-server (to let it serve a static HTML directory, to publish the ACME protocol challenge/response messages). But someone pointed out to me that TLS certificates are not bound to any specific port number (the theory being that if you can control port 80, you probably own the entire box anyways).

So I just need to run a normal webserver on the rendezvous server host, listening on port 80, and configure it to participate in the LetsEncrypt protocol for the public rendezvous URL domain (relay.magic-wormhole.io). That instance of certbot needs to write the certificate and private key into a place where wormhole-server can see it. Then wormhole-server (running on port 4000) can use the certificate without actually knowing anything about LetsEncrypt.

The order of operations needs to be:

* implement the webserver for certbot, get it running and making certificates
* implement TLS support in wormhole-server, make it possible to listen on both TLS and plain TCP at the same time (on different ports, 4000 and maybe 4443?)
* deploy it to relay.magic-wormhole.io
* implement client support
* commit a change to cli/public_relay.py, changing the URL to use `wss:` and point at the new port
* make a release

**Comment by M1n15try0f7ruth** [comment]
Am I right in the assumption that the first issue (the issue that a eavesdropper would be able to tell that a client is using magic-wormhole because of the public rendezvous server IP) has already been resolved via tor_manager.py but the second two have not?

I'm still trying to understand the project and trying to get my foot in the door of the project so that I could contribute at some point in the future.

**Comment by warner** [comment]
@Baeumla Yes, that's right. If you're using ``--tor``, then all IP addresses are hidden, which fixes the first issue. But the timing correlations exist even if you're using Tor.

**Comment by ManYsha** [comment]
Thank you sir.it worked when i executed after some time,i donno what's the
reason behind for that.And may i know what is --tor

On 25 Dec 2017 4:42 a.m., "Brian Warner" <notifications@github.com> wrote:

@Baeumla <https://github.com/baeumla> Yes, that's right. If you're using
--tor, then all IP addresses are hidden, which fixes the first issue. But
the timing correlations exist even if you're using Tor.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/warner/magic-wormhole/issues/144#issuecomment-353806921>,
or mute the thread

**Comment by warner** [comment]
`--tor` is the command-line flag to make your `wormhole` client use Tor for its connections instead of making direct TCP connections. It requires that Tor be installed, of course. `--launch-tor` will make it run a new copy of Tor (which usually takes 30-60 seconds to start up), or otherwise it will try to connect to a running Tor (which might take 10 seconds).

**Comment by warner** [comment]
.. and, when we do this, make it listen on port 443, as per #243. That should reduce the chances of an overly-aggressive firewall blocking it.

**Comment by n1trux** [comment]
>implement client support

shouldn't that be a priority? With docker you can easily put your wormhole installation behind a reverse proxy (like [letsencrypt-nginx-proxy](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) or [Traefik](https://traefik.io/)) which does TLS termination.

**Comment by warner** [comment]
Ok that adds the client-side support: using a `--relay-url=` of `wss://example.org/v1` will connect to port 443 over TLS. It seems to work with `--tor` as well.

The next step will be to run a TLS-terminating proxy in front of the public relay server. That proxy can also listen on port 80. I agree with the advice here: rather than having the `magic-wormhole-mailbox-server` speak TLS itself, we can use some other program to handle that part.

**Comment by piegamesde** [comment]
The stakes have recently increased with the add of permissions support: an eavesdropper could use this to steal credentials or the hashcash token to get illegitimate access to the rendezvous server.

Clients mostly support this out of the box already (since they're all using a potent WebSockets library), and I'd like to switch the default to `wss` for the Rust implementation.

So please add a TLS ending proxy to the public rendezvous server (I'm against having TLS support in the application itself). This also relates to https://github.com/magic-wormhole/magic-wormhole-mailbox-server/issues/24.

**Comment by gvegidy** [comment]
Another reason for switching to TLS could be browser security policies:

Let's say you wanted to implement a web browser based wormhole client, implemented in Javascript or Webassembly. You would then most probably publish the Javascript or Webassembly via HTTPS to prevent tampering with the code. Then this code is subject to web browser security policies that will usually prevent the script to connect to "insecure" websockets and enforce using TLS encrypted websockets.

There also is https://github.com/saljam/webwormhole which goes even further and uses WebRTC for the connections between the clients.

**Comment by meejah** [comment]
There's already TLS support in the application (via Twisted).

Indeed, the servers for Least Authority's service -- which does include a Web client (https://winden.app) -- are deployed on TLS partially for this reason.

To the point above, the default deployment would also need to deploy a version of the Transit server that supports WebSockets in order to support browser clients. (So, Winden can't use the default servers currently, because it only makes WebSocket connections)

**Comment by piegamesde** [comment]
Since this is a pure deployment issue and the software side of it has been resolved, can we close this? (Do we have a better place to track deployment issues?)

**Comment by meejah** [comment]
I do not; @warner if you want to continue to track this here please re-open.
