### ISSUE TITLE
Using a default relay server is potentially dangerous or unreliable

### ISSUE THREAD

**Issue by lf94** [magic-wormhole/magic-wormhole#399]
Hey! I think as a good suggestion to solve the above, one of the two following could be done:

1. Remove the default relay (not as preferable, which is understandable!)
2. Put it behind a flag (--use-default-relay)

I brought up this exact issue with https://github.com/schollz/croc/issues/277 but as you see the author has simply deleted the issue. Huge red flag to me.

Their reply was simply:

> See https://github.com/schollz/croc/blob/master/LICENSE re your questions

(GitHub is setup to send emails for any notifications for me, so I was able to save that.)

and then closed and deleted the issue.

croc says it takes inspiration from magic-wormhole, I hope this was not part of it :laughing:

**Comment by piegamesde** [comment]
- Please explain how the usage of the relay server might be dangerous
- How does removing the relay server mitigate this issue? Wormhole still needs one for functioning in many cases.
- How can the user experience not be massively downgraded by any fixes for this issue?

You may want to look into #150 and other related issues discussing this problem.

P.S.: You'll get responses to your issues about as good and polite as the issue itself.

**Comment by warner** [comment]
@lf94 thanks for the note!

There's a pretty direct usability/security tradeoff here, for sure, but I think it comes out in favor of continuing to use a baked-in default relay server.

The usability side of the tradeoff is:

The wormhole codes can be so short only because they assume both sides already have a common relay through which they can find each other. Within the context of that shared server, they only need a single number (the "4" in `4-purple-horseshoe`) to talk to each other, as opposed to anyone else who is using the server at the same time. If we couldn't assume that, the code would need to include a hostname too (and a port number if it wasn't a default). I feel that would make the codes much more difficult to recite and transcribe, because hostnames are not created with phonetic distinguishability in mind.

Plus, you must actually have a relay server to use, and it must have a public IP address. So before I can send you a file, I'd have to either choose a pre-existing relay server (and include its hostname in the code I tell you), or run one myself, which means renting a VPS somewhere, and/or registering a domain name, which is far beyond what a casual user can be expected to do.

The security side of the tradeoff is:

No matter which relay server you end up using, that server will be able to see the ciphertext of the messages you exchange. They'll be able to see your IP address, and that of your recipient (unless you use `--tor`). They can prevent your transfer from happening, by dropping or corrupting your messages.

If your connection happens to go through the transit helper as well (e.g. if neither you or your recipient has a public IP address), the transit helper gets to learn the same things, plus they learn the number of bytes you're transferring.

However, the protocol is designed to ensure that neither one can see the *plaintext* of your messages, modulo the [well-documented](https://github.com/magic-wormhole/magic-wormhole/blob/master/docs/attacks.md) "one guess per transfer" attack against the low-entropy wormhole code. The server gets no more power than an attacker who has taken over your local network, or the coffee-shop WiFi you're using. Unless you've done something unwise (and kinda anti-social) like running `wormhole send` in a script that automatically retries upon failure, you and your recipient will almost certainly give up on `magic-wormhole` well before this attacker has a reasonable chance of success, because they have a 65535-in-65536 chance of getting it wrong, and each time they guess wrong, you have to re-start the whole process with a new wormhole code.

Using your own relay server prevents *my* relay server from mounting this sort of attack, but it doesn't protect you against that coffee-ship WiFi attacker, or someone who manages to compromise *your* relay server. It's also not what protects your friends (whom you've invited to use your relay server) against *you*: that protection comes from the protocol and the cryptography, and is the same thing that protects you against me (as the operator of the default relay server).

So, given that using a non-default server makes the codes much much harder to convey from the human sender to the human recipient, and (I feel) doesn't improve the security significantly, I think the best approach is the one we're using: a baked-in default, with an easy way to override it if that's your thing (`wormhole --relay-url=YOURRELAY`, or set the `$WORMHOLE_RELAY_URL` environment variable).

@lf94 does that explanation feel ok to you?

**Comment by lf94** [comment]
That explanation is excellent. Thank you for taking the time to provide such educating documentation to users. You can close this issue :slightly_smiling_face:

**Comment by warner** [comment]
Awesome, thanks! Will do.
