### ISSUE TITLE
Relay server collapses after 200mb transfer

### ISSUE THREAD

**Issue by MrWormHole** [magic-wormhole/magic-wormhole#407]
I was transferring a file around 540mb in the UK, Transfer started to become slower(2mbs to 4kbs) around 200mb and it killed itself around 210mb. Is there a campaign to support relay servers or some sort of premium membership for high limits? I really like the convenience of this tool over ftp and scp

**Comment by piegamesde** [comment]
You can host your own relay server and use it through command line flags.

**Comment by MrWormHole** [comment]
Is there a guide for this?

**Comment by piegamesde** [comment]
https://magic-wormhole.readthedocs.io/en/latest/welcome.html#relays https://github.com/magic-wormhole/magic-wormhole-transit-relay/blob/master/docs/running.md

**Comment by warner** [comment]
FWIW, there's currently nothing in the public relay that throttles transfers or limits their size. I've considered adding it, because occasionally I see some truly enormous transfers, but I haven't gotten around to it so far.

The one thing that might cause a relay-using transfer to fail could be if the relay host is rebooted (for maintenance or something). I try pretty hard to only reboot it when nobody is using it, but every once in a while something happens when I'm not looking and it might break a transfer.

It's also possible that your local ISP (on one or both ends) is forging RST packets or something to throttle/terminate connections. That would be pretty horrible of them, but I've heard of it happening elsewhere.

We have background plans (#6) to add some sort of NAT hole-punching to allow a larger fraction of connections avoid using the relay, and instead make direct client-to-client connections. That wouldn't help with whatever your ISP might be doing to you, but it would let your transfer be independent of the public relay.

I don't think there's anything we can do on the client/relay/protocol side to help this one, alas, so I'm going to close this ticket. Good luck!
