### ISSUE TITLE
Slow program startup (`wormhole help` takes ~250ms)

### ISSUE THREAD

**Issue by lokegustafsson** [magic-wormhole/magic-wormhole#438]
I just tried magic wormhole and was surprised by the latency for even very simple commands.
```
$ time wormhole
Usage: wormhole [OPTIONS] COMMAND [ARGS]
...
real	0m0.254s
user	0m0.240s
sys	0m0.014s
```
I think 250 ms overhead before actually doing anything is totally unacceptable. Especially when just querying the help page. The system part of the time is mainly `newfstatat`, loading python source files from disk and the like. I guess most of the user time is spent actually parsing that code and/or doing initialization.

Could some dependency loading perhaps be done lazily? Or perhaps dependencies could be eliminated or replaced with leaner alternatives? I do not know enough python packaging or other internals to know what exact approach to take.

At the very least, I think you should measure this, avoiding regressions and setting a goal of actually reducing this somehow.

Thanks for maintaining magic wormhole. Cheers

**Comment by warner** [comment]
Yeah, that startup time is a drag. It's even worse on slower systems like a Raspberry Pi (an rpi4 takes 2.3s cold, 1.2s the second time.. an rpi3 takes 3.8s cold and 2.7s warm).

You're right that a lot of this is just Python, and the fact that the standard startup/import process needs to load (and parse) every bit of code that the program will ever need, just in case. There *are* ways to do lazy loading, but I think they'd add a non-trivial amount of complexity. It might be worth an experiment, but you'd have to remove the top-level imports from every `__init__.py`, and flip the source tree around so that the CLI libraries are at the top level, and they only import the lower-level directories if they actually do something.

Dependencies are, as always, a tradeoff between coding-convenience / modularity / division-of-labor / best-practices on one hand, and narrowness-of-purpose / efficiency on the other. We use Twisted because it has mature robust tools for every bit of networking and general application launch behavior that we need. There is probably some Twisted code that gets loaded which we don't need, and that adds to the startup time. But writing our own subset of Twisted, just to avoid that, would almost certainly introduce bugs that the Twisted crowd fixed a decade ago, and wouldn't benefit from improvements that they'll make in the future. So as tradeoffs go, I think we picked the right one.

I suspect that 250ms is about as fast as practical for the startup of a moderate-complexity Python program. `wormhole` is a bit unusual in that it's only really ever used interactively (there's a human in the loop, to transcribe the wormhole code to/from the remote system), and it's not like the human can react fast enough to benefit from launching faster, so I'm not sure I can imagine a use case that would be worth the complexity of banging on this a whole lot.

That said, the ports to compiled languages (Rust, Go) are likely to be faster, if that seems important. And I very much do like the idea of treating startup time as a benchmark to track, so that any dependency changes we consider making will need to strongly justify their effects on the startup time.

Closing because I don't think we can do anything concrete on this now. Thanks!
