### ISSUE TITLE
Memory overuse in wormhole receive

### ISSUE THREAD

**Issue by hectorBrown** [magic-wormhole/magic-wormhole#447]
Trying to send a large (11.2GB) directory makes the receiving machine seize up.
Monitoring in htop, I can see the receive process taking up more and more memory.
Strangely, during compression and sending, the sending machine keeps memory to a reasonable, if not small, amount.

**Comment by piegamesde** [comment]
Are you sending a single file or a directory?

**Comment by hectorBrown** [comment]
> Are you sending a single file or a directory?

Sorry, directory, edited original issue.

**Comment by meejah** [comment]
I haven't investigated deeply, but I strongly suspect this is a Python issue with how Zip files work? (That is, the receiving side is receiving a Zip file but IIRC you need the "end" of the file before you can unzip it .. so I'm suspecting that Python is accumulating the bytes in memory).

Does it take something like 12GB of memory by any chance?

Although this will be eliminated by sending files-in-directories individually (thus removing the need for "zip") in the next-generation transfer protocol it would be nice to have a solution for this in the current protocol.

**Comment by hectorBrown** [comment]
Would it not be possible to cache the zip file to disk and then unzip it after if it is very large, why would it all happen in memory?

Yeah, not that I have 12GB, but it seems to always take the exact size of the zip file. 

I assume other large files are written as they are received then? I can't test this at the moment.

**Comment by meejah** [comment]
Yeah, in principal that's certainly what _should_ happen. Non-ZIP files are streamed to disk, yes.

**Comment by PrSunflower** [comment]
Hello, trust you are all well. :wave: 

This discussion is useful for me, I have witnessed strange behaviours when transferring large directories. My biggest problem is that the transfer is paused multiple times because the Receiver's RAM is full (or something similar). And these are looong pauses, considerably slowing down my workflow.

The thing is, my only use of Magic-Wormhole **is** transferring 10 GiB directories through LAN (Ethernet 1Gbps).

- Do you have suggestions for me?
- Am I no using MW in an optimal way?
- Maybe MW is not even the right tool for me?

**Comment by psanford** [comment]
You could try an alternative client. [wormhole-william](https://github.com/psanford/wormhole-william) won't hold the full contents of files in memory so it should not have this issue. I'm not sure if the rust implementation does this but you could also try that.

You can also compress the folder yourself before sending it. That way Magic Wormhole would stream the file to disk and shouldn't run out of memory.

**Comment by piegamesde** [comment]
The [Rust implementation](https://github.com/magic-wormhole/magic-wormhole.rs) does not build any temporary files, so it is light on memory and disk usage. The downside is that it sends directories as tar balls instead of zip files (as the latter cannot be streamed without creating temporary files), creating a slightly worse user experience because you manually have to unpack it. Also directory sending is currently broken on the latest release, a fix can be found on the `develop` branch. Sorry about that.

**Comment by meejah** [comment]
You could already stream tarballs with the Python client too.

The real "ask" here is to continue to support "sending a directory" but with a low-level primitive that _isn't_ Zip or (since that's a protocol change) use a Python library that doesn't stream it into memory (i.e. instead streaming to tempfiles on disk before unzipping, using twice as much disk space).

Medium-term the proper fix will be the next-generation file-transfer protocol. (See e.g. https://github.com/magic-wormhole/magic-wormhole/pull/445 )

**Comment by piegamesde** [comment]
> You could already stream tarballs with the Python client too.

No. With "streaming" I mean "build the tar ball on the fly while sending so that you don't have to use twice the storage while sending"

**Comment by meejah** [comment]
> With "streaming" I mean "build the tar ball on the fly while sending so that you don't have to use twice the storage space"

Yes, you could use a FIFO to do this already with the Python implementation too (but, it's still non-standard in the protocol so you'll just end up with a tarball on the other end, right?)

**Comment by piegamesde** [comment]
Nope, a FIFO wouldn't work because the protocol wants you to know the file size in advance. The trick is that tar files are easy to build and deterministic, so you can walk the directory structure and calculate how large it would be without actually having to store the temporary file.

**Comment by meejah** [comment]
Ah, right, size ...

**Comment by PrSunflower** [comment]
Thank you for your replies you 3  :slightly_smiling_face: 

I'd be pretentious if I said I followed everything... But I'm noting down those points:

- Don't send a directory, compress it into a file
- Try wormhole-william
- Try Rusty Wormhole (only the development branch for the moment)
- Wait patiently for the next-gen file-transfer protocol in Magic Wormhole

Thanks :slightly_smiling_face: 

I have to be honest, that's a lot of time that I'll invest researching & learning. I think I'll also consider other ways, like an FTP server :sweat_smile:   

Even though I really like the concept of MW, for my use other tools may be easier to deploy... :sweat_smile:

**Comment by meejah** [comment]
Also, to be clear: I would like the Python implementation to be fixed in this regard too (hence, leaving this ticket open).

Technically, nothing prevents streaming a large Zip file to _disk_ and then unzip it -- I think it's just an accident of the way we're using (or limitations of) the Python zip library..

**Comment by vu3rdd** [comment]
Does this library [zipstream](https://github.com/allanlei/python-zipstream) look like a good replacement for the built-in zip?

**Comment by meejah** [comment]
Upon closer investigation, this is a pretty shallow issue -- not passing the correct argument to `SpooledTemporaryFile` (like the send-side already does).

@hectorBrown can you re-test with the associated branch and let me know if this solves your problem?

(If you used `pip` to install this originally, you can use a command-line like `pip install https://github.com/meejah/magic-wormhole/archive/refs/heads/447.memory-directory.zip` to install that branch)

**Comment by hectorBrown** [comment]
As far as I can tell the fix works for me, memory stays constant throughout. Don't have another machine to send to at the moment though so just tried sending a file full of random data to myself, hoping that's virtually the same thing.
Thanks!

**Comment by meejah** [comment]
Great, thanks for the follow-up ... and yeah, that should be approximately the same as sending to another computer (for this code-path). :christmas_tree:

**Comment by PrSunflower** [comment]
Hi people :slightly_smiling_face: ,  thank you very much, meejah :tada: 

I am not a developer and I don't know my way around Python (am running Debian Testing, Python is not installed by default).
Is there an easy way I could use MW with the #470 fix?

**Comment by meejah** [comment]
@PrSunflower not necessarily "easy" but this procedure should work (I'm on debian bookworm):

```
sudo apt install python3-full python3-virtualenv
virtualenv /tmp/venv
/tmp/venv/bin/pip install https://github.com/magic-wormhole/magic-wormhole/archive/refs/heads/master.zip
/tmp/venv/bin/wormhole send
```

You could replace the `/tmp/venv` with something else more permanent if you want. That directory can be entirely deleted (and contains all the Python stuff necessary to run `wormhole). Happy to help further if need be :)
