### ISSUE TITLE
Question: Why isn't "--verify" a default for the send subcommand?

### ISSUE THREAD

**Issue by alanxoc3** [magic-wormhole/magic-wormhole#469]
There are two attacks described here (man in the middle and DoS):
https://magic-wormhole.readthedocs.io/en/latest/attacks.html

But I see another pretty easy attack. If someone just picks a few passwords and checks the server every few seconds for those password, they could connect to a random sender and receive files before the receiver is able to connect. Without the '-v' option, the sender will automatically finish sending smaller files to the attacker before they realize they connected to the wrong person.

I could imagine an attacker having reasonable success after running their script for a while (a few days?), assuming there are enough users using the the default settings (65536 possible passwords by default, guessing every second will take about 18 hours to guess 65536 times).

Sure you could detect a spamming IP from the server side, but then the attacker could just use something like tor to keep changing their ip addresses instead. That also would further complicate the server implementation & maintainability.

It seems like a reasonable default to me to require the "-v" option, it's just an extra y/n prompt for the sender, not really a big deal since this tool is meant for a single person moving files between computers or two people sharing files between each other in real time.

**Comment by meejah** [comment]
The verifier is only useful if both sides are willing to do it. (That is, it can make you be more sure that you have the correct recipient -- but only if you actually confirm the verifier string -- presumably via whichever channel you used to send the code in the first place).

I can't personally speak to _why_ the default is to not verify (versus e.g. a `--no-verify` option). I'm also not sure if any clients _besides_ the Python one actually implements this check (i.e. gives their human a chance to verify the strings before proceeding).

Practically speaking, this would be a breaking change to the CLI and I'm not sure if it's worth it at this point..?

**Comment by piegamesde** [comment]
I think we should rather put our focus on how to make an attack harder. By using a longer –and while we're at it: better– wordlist for example we could easily increase the password strength to 20 bits. Additionally, the server should have better protection against brute forcing passwords. (Note that the latter won't help against a threat model where the server itself is malicious)

In the end, while attacks are not technically unfeasible they are very *unappealing*: You can't control which files you'll get so you'll end up with receiving worthless junk most of the time. And you'd end up DOSing >99.99% of the traffic so users would probably wander off to different services quickly. (This also shows again how vulnerable we still are to DOS attacks)

**Comment by meejah** [comment]
Not sure what you're getting at with "brute-forcing passwords": you only get one try (even if you are a malicious server).

The wordlist and DoS is off-topic here: this is about the post-connection verifier, which allows the humans to confirm that they are indeed talking to the correct recipient who definitely has the correct key (e.g. to subvert the described MitM attack in the link above). The extra security gained in this way is at the expense of usability (and is orthogonal to the security arguments of the length of default keys).

Also, you can already use any size password you like, if you wish to (which is in the description above too).

**Comment by alanxoc3** [comment]
Increasing the default password strength would help make this less of a concern, but not resolve it completely. Also, the go client (wormhole-william) implements the verify option too, but it's also not a default there.

I'm a bit paranoid, so I've always been using the verify option (just takes a few extra seconds checking the verification string). However I feel bad if a new user used the tool defaults to send some files containing sensitive information (credit card/bank info or maybe api keys) and had their information accidentally stolen.

And yeah, maybe it's not worth it at this point. But thought I'd put the idea out there.

**Comment by meejah** [comment]
At some point, we have to decide what chance of failure is "good enough". At 2^256 it's just equivalent to BIP32 or similar encoding the entire (random) symmetric key -- so there's no usability improvement over simply exchanging full-strength keys.

Others have made the argument that 2^16 is good enough; one could argue whether it's worth changing that to e.g. 2^24 (by adding another word) or not. Better security? Yes, absolutely. But: less usable. Similar as you add more words (and of course, you can already choose to do that if you believe 1/65536 is good odds or have reason to believe you're being attacked). With two words, there's a 0.0015% chance of the attacker winning.

Similar for the verifier: if you (successfully, and accurately!) always verify then you've got 0% of the attacker winning. But, it's hard to do that (successfully, accurately, always).

While I didn't choose the defaults, I do think they're a good compromise: it's pretty easy to use (a design goal) and pretty secure. For users who are willing to do a little more work, they can be way more secure -- but I think keeping that optional is good. Part of that is decision fatigue. If the humans aren't actually willing to do the work (of verifying), getting them used to clicking "sure, I verified" is actually _worse_ than useless because they might easily click/type past a different but more serious warning.

(For example, how many "safety numbers" have you verified when using Signal? There are _some_ I will, if we're nearby, but largely I do not do that).

Note that for _some_ use-cases -- like exchanging a file with a device you're sitting beside -- confirming the verifier is really easy. But if you've phoned a friend and are exchanging a file that way, reading the verifier can easily be the most time-consuming part.

I'd certainly love to see more ways to display verifiers (or other ideas to make them easier to use) especially for use-cases where you can't see both devices at once but I do believe the keeping it optional is the right choice now.

**Comment by piegamesde** [comment]
Speaking of tradeoffs: if we let go of the "no identity" requirement, one could build a feature that skips the verification when the sender knows the receiver from a previous transfer, and otherwise show it. That's by the way why I consider verifying Singal contacts (or any other messaging service that implements it) as optional: Most of the time I can do TOFU and all I want to know is when the identity suddenly changes.

**Comment by alanxoc3** [comment]
That's an interesting idea @piegamesde. Similar to how SSH works. It would introduce state (store things on disk) that I don't think was in magic wormhole before though.

**Comment by meejah** [comment]
(This wouldn't replace the "verifier" exactly, but it would allow you to "re-use" a session with full-strength random mailbox and full-strength ephemeral key .. but a "verify" step could also be part of saving a Seed, and maybe "recommended" or "on by default")
